twig:
    default_path: '%kernel.project_dir%/templates'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'

when@test:
    twig:
        strict_variables: true
